project_id = "jhrsmjlvzfzdfbdfhwss"

[functions.stripe-checkout]
verify_jwt = false

[functions.verify-purchase]
verify_jwt = false

[functions.referral-link]
verify_jwt = false

[functions.sync-stripe-price]
verify_jwt = false